version: '3'

services:
  mariadb:
    image: mariadb:10.11.13
    container_name: moodle_db
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodlePassword123
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: moodle_phpmyadmin
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      - "8081:80"

  moodle:
    build: .  # This tells docker-compose to build from the Dockerfile in current directory
    container_name: moodle_app
    depends_on:
      - mariadb
    environment:
      # Database connection settings
      MOODLE_DATABASE_HOST: mariadb
      MOODLE_DATABASE_PORT_NUMBER: 3306
      MOODLE_DATABASE_USER: moodle
      MOODLE_DATABASE_NAME: moodle
      MOODLE_DATABASE_PASSWORD: moodlePassword123
      
      # Moodle admin settings
      MOODLE_USERNAME: admin
      MOODLE_PASSWORD: AdminPass123
      MOODLE_EMAIL: admin@example.com
      
      # Allow empty password for development
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - moodle_data:/bitnami/moodle

volumes:
  db_data:
  moodle_data: